version: "3.7"

services:
  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - medicalapp-network

  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    links:
      - db:db
    ports:
      - "8000:8000"
    networks:
      - medicalapp-network

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    links:
      - db:db
    depends_on:
      - django_gunicorn
    networks:
      - medicalapp-network

volumes:
  static:
  postgres_data:

networks:
  medicalapp-network:
    driver: bridge
