version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static:/static
    env_file:
      - .env

    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=${NAME}
      - DATABASE_USER=${USER}
      - DATABASE_PASSWORD=${PASSWORD}
      - DATABASE_HOST=${HOST}
      - DATABASE_PORT=${PORT}
    networks:
      - mynetwork

volumes:
  postgres_data:
  static:

networks:
  mynetwork:
