version: "3.7"

services:
  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static:/static
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    networks:
      - mynetwork

volumes:
  static:
  postgres_data:

networks:
  mynetwork:
