# Generated by Django 4.1.1 on 2023-05-02 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='id_tipo_medicion',
            field=models.ForeignKey(db_column='idTipoMedicion', default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.tipomedicion'),
        ),
    ]
