# Generated by Django 4.1.1 on 2023-05-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_medicion_id_tipo_medicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='afi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
