# Generated by Django 4.1.7 on 2023-05-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reporte_afi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetoMedicionDiagnostico',
            fields=[
                ('idfetomediciondiagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('hc_hadlock', models.CharField(db_column='hc_hadlock', default='', max_length=100)),
                ('bpd_hadlock', models.CharField(db_column='bpd_hadlock', default='', max_length=100)),
                ('cm', models.CharField(db_column='cm', default='', max_length=100)),
                ('vp', models.CharField(db_column='vp', default='', max_length=100)),
                ('va', models.CharField(db_column='va', default='', max_length=100)),
                ('afi', models.CharField(db_column='afi', default='', max_length=100)),
                ('cereb_hill', models.CharField(db_column='cereb_hill', default='', max_length=100)),
                ('efw', models.CharField(db_column='efw', default='', max_length=100)),
                ('csp', models.CharField(db_column='csp', default='', max_length=100)),
                ('reporte', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.reporte')),
            ],
            options={
                'verbose_name_plural': 'FetoMedicionDiagnostico',
                'db_table': 'FetoMedicionDiagnostico',
            },
        ),
    ]
