# Generated by Django 4.1.7 on 2023-05-11 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fetomediciondiagnostico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='bdp_hadlock_1',
            new_name='bpd_hadlock_1',
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='bdp_hadlock_avg',
            new_name='bpd_hadlock_avg',
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='bdp_hadlock_dev',
            new_name='bpd_hadlock_dev',
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='bdp_hadlock_edc',
            new_name='bpd_hadlock_edc',
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='bdp_hadlock_ga',
            new_name='bpd_hadlock_ga',
        ),
    ]
