# Generated by Django 4.1.1 on 2023-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_paciente_lmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='motivo_consulta',
            field=models.CharField(default='Ultrasonido de control', max_length=1000),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='txtresults',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
