# Generated by Django 4.1.1 on 2023-05-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_consulta_motivo_consulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embarazo',
            fields=[
                ('id_embarazo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_embarazo', models.PositiveIntegerField(default=0)),
                ('idpac', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.paciente')),
            ],
            options={
                'verbose_name_plural': 'Embarazos',
                'db_table': 'Embarazo',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='idembarazo',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.embarazo'),
        ),
    ]
