# Generated by Django 4.1.7 on 2023-06-01 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_embarazo_consulta_idembarazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feto',
            fields=[
                ('idfeto', models.AutoField(primary_key=True, serialize=False)),
                ('id_embarazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.embarazo')),
            ],
            options={
                'verbose_name_plural': 'Fetos',
                'db_table': 'Feto',
            },
        ),
    ]
