# Generated by Django 4.1.7 on 2023-06-01 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_feto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='idreporte',
        ),
        migrations.AddField(
            model_name='reporte',
            name='consultaid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.embarazo'),
            preserve_default=False,
        ),
    ]
