# Generated by Django 4.1.7 on 2023-06-01 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_consulta_idreporte_reporte_consultaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='idfeto',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='bpd_hadlock_avg',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='bpd_hadlock_dev',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='bpd_hadlock_edc',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='bpd_hadlock_ga',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='cereb_hill_avg',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='cereb_hill_dev',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='cereb_hill_edc',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='cereb_hill_ga',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='cm_avg',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='csp_avg',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='hc_hadlock_avg',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='hc_hadlock_dev',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='hc_hadlock_edc',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='hc_hadlock_ga',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='va_avg',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='vp_avg',
        ),
        migrations.AddField(
            model_name='feto',
            name='posicion_feto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fetoid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.feto'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='consultaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.consulta'),
        ),
        migrations.DeleteModel(
            name='Historiaclinica',
        ),
    ]
