# Generated by Django 4.1.1 on 2023-09-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_personalsalud_cedulamed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_data',
            field=models.FileField(upload_to='ultrasond_images/'),
        ),
    ]
