# Generated by Django 4.2.13 on 2024-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_images_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='ga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='hallazgo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='images',
            name='sexo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='images',
            name='tipo_examen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_data',
            field=models.FileField(upload_to='ultrasound_images/'),
        ),
    ]
